services:
  airflow:
    image: apache/airflow:3.0.0-python3.12
    ports:
      - "8080:8080"
    volumes:
      - ./simple_auth_manager_passwords.json:/opt/airflow/simple_auth_manager_passwords.json
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    environment:
      # https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#configuration-reference
      AIRFLOW__API__HOST: "0.0.0.0"
      AIRFLOW__API__PORT: "8080"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE: "/opt/airflow/simple_auth_manager_passwords.json"
      AIRFLOW__CORE__LOAD_EXAMPLES: False
      AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: "/opt/airflow/logs"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: True
    command: bash -c "airflow standalone"